//
// Generated file, do not edit! Created by nedtool 5.6 from fico4omnet/linklayer/can/messages/ErrorFlag.msg.
//

#ifndef __FICO4OMNET_ERRORFLAG_M_H
#define __FICO4OMNET_ERRORFLAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace FiCo4OMNeT {

/**
 * Class generated from <tt>fico4omnet/linklayer/can/messages/ErrorFlag.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ErrorFlag
 * {
 *     int someField;
 *     string anotherField;
 *     double arrayField1[];
 *     double arrayField2[10];
 * }
 * </pre>
 */
class ErrorFlag : public ::omnetpp::cPacket
{
  protected:
    int someField;
    ::omnetpp::opp_string anotherField;
    double *arrayField1; // array ptr
    unsigned int arrayField1_arraysize;
    double arrayField2[10];

  private:
    void copy(const ErrorFlag& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ErrorFlag&);

  public:
    ErrorFlag(const char *name=nullptr, short kind=0);
    ErrorFlag(const ErrorFlag& other);
    virtual ~ErrorFlag();
    ErrorFlag& operator=(const ErrorFlag& other);
    virtual ErrorFlag *dup() const override {return new ErrorFlag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSomeField() const;
    virtual void setSomeField(int someField);
    virtual const char * getAnotherField() const;
    virtual void setAnotherField(const char * anotherField);
    virtual void setArrayField1ArraySize(unsigned int size);
    virtual unsigned int getArrayField1ArraySize() const;
    virtual double getArrayField1(unsigned int k) const;
    virtual void setArrayField1(unsigned int k, double arrayField1);
    virtual unsigned int getArrayField2ArraySize() const;
    virtual double getArrayField2(unsigned int k) const;
    virtual void setArrayField2(unsigned int k, double arrayField2);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ErrorFlag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ErrorFlag& obj) {obj.parsimUnpack(b);}

} // namespace FiCo4OMNeT

#endif // ifndef __FICO4OMNET_ERRORFLAG_M_H

